#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Скрипт для настройки переменных окружения для Telegram бота
"""

import os
import json

def setup_environment():
    """Настройка переменных окружения"""
    print("🔧 Настройка переменных окружения для Telegram бота")
    print("=" * 50)
    
    # Проверяем существующий .env файл
    env_file = '.env'
    env_data = {}
    
    if os.path.exists(env_file):
        print(f"📁 Найден существующий файл {env_file}")
        with open(env_file, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    env_data[key] = value
    
    # Запрашиваем BOT_TOKEN
    print("\n🤖 Настройка токена бота:")
    if 'BOT_TOKEN' in env_data:
        print(f"   Текущий токен: {env_data['BOT_TOKEN'][:10]}...")
        change = input("   Изменить токен? (y/N): ").lower().strip()
        if change == 'y':
            new_token = input("   Введите новый токен бота: ").strip()
            if new_token:
                env_data['BOT_TOKEN'] = new_token
    else:
        new_token = input("   Введите токен бота: ").strip()
        if new_token:
            env_data['BOT_TOKEN'] = new_token
    
    # Запрашиваем ADMIN_USER_ID
    print("\n👤 Настройка ID администратора:")
    if 'ADMIN_USER_ID' in env_data:
        print(f"   Текущий ID: {env_data['ADMIN_USER_ID']}")
        change = input("   Изменить ID? (y/N): ").lower().strip()
        if change == 'y':
            new_id = input("   Введите ваш Telegram ID: ").strip()
            if new_id:
                env_data['ADMIN_USER_ID'] = new_id
    else:
        new_id = input("   Введите ваш Telegram ID: ").strip()
        if new_id:
            env_data['ADMIN_USER_ID'] = new_id
    
    # Сохраняем в .env файл
    with open(env_file, 'w', encoding='utf-8') as f:
        f.write("# Telegram Bot Environment Variables\n")
        f.write("# Generated by setup_env.py\n\n")
        
        for key, value in env_data.items():
            f.write(f"{key}={value}\n")
    
    print(f"\n✅ Файл {env_file} обновлен!")
    
    # Создаем файлы данных если их нет
    print("\n📁 Инициализация файлов данных...")
    
    files_to_create = {
        'notifications.json': {},
        'bot_settings.json': {
            'daily_summary_time': '09:00',
            'timezone': 'Europe/Moscow'
        },
        'price_history.json': {}
    }
    
    for filename, default_data in files_to_create.items():
        if not os.path.exists(filename):
            with open(filename, 'w', encoding='utf-8') as f:
                json.dump(default_data, f, ensure_ascii=False, indent=2)
            print(f"   ✅ Создан {filename}")
        else:
            print(f"   📁 {filename} уже существует")
    
    print("\n🎉 Настройка завершена!")
    print("\n📋 Следующие шаги:")
    print("1. Убедитесь, что файл .env содержит правильные данные")
    print("2. Запустите бота: python admin_bot.py")
    print("3. Отправьте /start боту")
    print("4. Для тестирования ежедневной сводки используйте /test_daily")

if __name__ == '__main__':
    setup_environment() 